Added subs check and parsing
evgeni/katello-attach-subscription pull request #15
Opened 2016-11-25 00:33 UTC by Rocco83

Now any string is parsed, even subs ids.
the key for the yaml has changed to keep both keys for debug.

This solve also https://github.com/RedHatSatellite/katello-attach-subscription/issues/14

@evgeni can you please check has_resource on your side?
on latest sat 6.2 seems that host_subscriptions exists, so 
if api.has_resource?(:host_subscriptions)
is true.

2017-06-05 22:34 UTC, Rocco83 commented
Hi,

The function has been rebased and improved.
Some tests has been done.
Code has been speeded up by moving one api call only when really needed (sys = ).
Changed --use-cache in --read-from-cache
Added sanity check
Added --verbose flag
Fixed (hopefully) indentations -- some may be still wrong, especially for DEBUG

Well... major rewrite i would say.

2017-06-06 09:51 UTC, evgeni requested changes

2017-06-06 09:51 UTC, evgeni commented on katello-attach-subscription
> +  opts.on("-d", "--debug", "debug output for the script") do
I think `--debug` should just set `verbose=true` too, so you don't have to do `if verbose or debug` everywhere

2017-06-06 09:51 UTC, evgeni commented on katello-attach-subscription
> +  if @yaml[:type] = "Hypervisor"
Where does that come from? We don't define `type` directly in the YAML, just in the individual subscription sections

2017-06-06 09:51 UTC, evgeni commented on katello-attach-subscription
> +    puts " Started parsing entry #{subcurrentcount}#{subsyamltotalentry}"
missing separator between current and total?

2017-06-06 13:35 UTC, Rocco83 commented on katello-attach-subscription
> +  opts.on("-d", "--debug", "debug output for the script") do
Ok sounds good. Will be done shortly.

2017-06-06 13:35 UTC, Rocco83 commented on katello-attach-subscription
> +    puts " Started parsing entry #{subcurrentcount}#{subsyamltotalentry}"
Yes thanks

2018-03-08 11:14 UTC, Rocco83 commented
Seems that i cannot mark it somehow as resolved, but it is resolved since https://github.com/RedHatSatellite/katello-attach-subscription/pull/15/commits/3fd34e025fc65a4dc6540fcebff2353183dfd3a8
@evgeni may you please commit ? :)

2018-12-07 09:03 UTC, evgeni commented
I think this was part of #26, closing

2018-12-07 09:03 UTC, closed without merging